### PR TITLE
Adding JPBB Options and Online execs

### PR DESCRIPTION
**Pull request by nolrinale**
Adds to the Japanese localization resources the original Online.exe and Option.exe from the latest official JPBB client.

This latest option.exe allows the user to enable/disable previously unavailable settings such as Word Wrap and Global Focus Sound 

These files are meant to be used with an untouched Tethealla12513 client

### CODE REVIEW

**Comment by fuzziqersoftware** [comment]
I think in general we shouldn't add compiled executables to the repository, with the only exception being GBA files intended to be served to PSO GC clients. Is there an existing copy of these files (perhaps in an installer on archive.org) that we could link to instead?

**Comment by Matt-Swift** [comment]
GitHub doesn't care about executables in the repo, I would just suspect that fuzziqer wants to err on the side of caution when it comes to potentially directly distributing them.

Having a BB installer linked somewhere is a good idea, especially since Tethealla took down all their downloads - I can offer to host them to have them linked to, plus I can have archive deliberately scrape so they also have a copy for future preservation purposes if something was to come to pass.

**Comment by nolrinale** [comment]
I dont have resources for hosting the client beyond what we have here on github, but if you want you can get these two and upload a new tethealla client including them maybe add them in a zip file called "japanese files" so nobody complains their options and launcher are in japanese by default. 

I'm just adding all these to preserve as much as possible from PSOBB as we can. 
Let me know if you are willing to do it and I close this PR instead

**Comment by Matt-Swift** [comment]
What I've done is hosted versions of playable clients (that people actually want, not necessarily straight vanilla installers) at the following links:
- TethVer12513 in English: https://ragol.org/files/bb/TethVer12513_English.zip ([Archive Link](https://web.archive.org/web/20231106212138/https://ragol.org/files/bb/TethVer12513_English.zip))
- TethVer12513 in Japanese: https://ragol.org/files/bb/TethVer12513_Japanese.zip
- US 1.24.3: https://ragol.org/files/bb/USVer1243.zip

The Japanese client contains the localisation files provided by @nolrinale, as well as the online and option executables provided in this PR.

All 3 clients have been patched to point at 127.0.0.1 as well, so they should work out of the box for anyone hosting a local server on the same system - I would suspect anyone trying to host a server elsewhere would know how to find this and hex edit it out.

The only change for the US BB client is that PsoBB.exe was changed to one with GameGuard patched out. To launch it, PsoBB.exe must be ran directly, as online.exe will try to launch GameGuard before opening the client.

I'm currently uploading the other two clients to an archive snapshot so they're preserved if something was to happen.

**Comment by nolrinale** [comment]
Thanks a lot for providing these Matt, I will close this PR, for the sake of completion maybe you can try making another PR updating the README or by adding a txt file inside the psobb notes folder with these links

**Comment by MADrewry** [comment]
I hate posting comments on a closed pr but I don't know where else I can post this, and I think it is useful info that may avoid some frustration.

The US 1.24.3 client appears to have a broken common.pac file in the data\sound folder. I have tried on Windows 10 and 11 and the game will not run with that file in place. Removing or renaming the file will allow the game to run. Replacing it with the common.pac file from the Tethealla client will also allow the game to run.

I believe the common.pac file is corrupt as it is the only file that I am unable to open with a pac viewer. Notably I have come across this same issue with US client downloads from multiple sources, as of yet I have not found an "original" US PSOBB client that does not have this issue.

Also, thanks for providing these files as they are a valuable resource.

**Comment by Matt-Swift** [comment]
Right, the common.pac file for the US client is messed up, I actually knew this already and forgot to fix that download. Looking at it compared to the working one, it appears there are a lot of missing bytes which reference the data folder - does the game not even load to the patch server? Would be a huge oversight if so as you wouldn't be able to get a fixed file from the patch server.

Regardless, I've re-uploaded (and re-archived) the client with the Tethealla common.pac for now since it works; I don't feel like trying to fix the common.pac file although I suspect it's just filling in the missing bytes where they are zero'd out.

As for putting these links in the Readme or Notes - I am fine with this, but it depends if fuzziqer wants to be linking to game binaries from his repository.

**Comment by MADrewry** [comment]
@Matt-Swift, to answer your question; untouched, the US client bombs out immediately without ever getting to the patch server. However - and I forgot to mention this earlier - by going into options beforehand and disabling sound the game will run normally (albeit without sound) 

@nolrinale that is some interesting information that I was unaware of. I'm certain finding those flags are beyond my skill but it would be an interesting exercise.

**Comment by MADrewry** [comment]
@Matt-Swift, to answer your question; untouched, the US client bombs out immediately without ever getting to the patch server. However - and I forgot to mention this earlier - by going into options beforehand and disabling sound the game will run normally (albeit without sound) 

@nolrinale that is some interesting information that I was unaware of. I'm certain finding those flags are beyond my skill but it would be an interesting exercise.

**Comment by MADrewry** [comment]
@Matt-Swift This is more a curiosity than anything: Taking a clue from what you said about the missing data folder info in the common.pac file, I took a look at it. It seems path info is simply missing from the file. I assume PsoBB.exe is referencing the relative path info to find the sound tracks, rather than replace the path info for every track in the file I got an idea and moved the common.pac file into the same folder as the PsoBB.exe file and the program runs normally.

**Pull request closed without merging**
