### PR TITLE
Added all the missing JP quests for BB

### PR DESCRIPTION
**Pull request by nolrinale**
This PR continues the previous PR adding the missing Japanese quests for Blue Burst and in addition also:

- Adjusts the order of Retrieval quests in EP1
- Removed Duplicate Maximum Attack 2 in EP2
- Organizes all the Solo EP4 quests under the Solo category rather then Story
- Adds the Gallon Shop Valentine Edition quest to EP2 shops during Valentine
- Adds the missing Festivity on The Beach quest in EP2 events and removes the incorrect Singing By the Beach in its place.

### CODE REVIEW

**Comment by Matt-Swift** [comment]
Some notes:

1. I wouldn't move the retrieval quests that you did (the Hopkins lost ones) - the reason they had their other server number (58 to 60) was because that was the internal number for the quests on Dreamcast. Keep them the same otherwise you're using up internal server numbers you don't need to be; don't forget newserv isn't just for BB. I personally made the decision to make Lost Hell Pallasch 61 on all versions for sort.
2. The "duplicate Maximum Attack 2" (q211) that you removed is different to Maximum Attack 2 Ver2, and even features an area not in MA2V2 in CCA. I would not remove this, it's the original event version.
3. Is there a reason Missing Maracas (q068) was removed?
4. Singing by the Beach is an older version of Festivity on the Beach right? I would also not remove this; while it is superseded, I would suspect that the newserv project is more interested in preserving these than removing them.

**Comment by fuzziqersoftware** [comment]
Thanks for adding the missing quest versions; it will be good to have a more complete quest library. The quests you're moving to solo-extra in this PR should have been there in the first place; I don't know how I missed that originally.

However, I think we should make some changes here, as Matt suggested:
1. We should keep the quest numbers the same on all versions; if a BB quest also exists on previous version, we should use the previous version's quest number for it (for example, Lost HEAT SWORD should be quest 58 on all versions). For preservation purposes it's not important to keep the original quest numbers, since for BB, the quest number really has no meaning - it's only relevant on console versions for deduplicating download quests.
2. We should keep both versions of MA2 since there are significant differences.
3. We shouldn't delete any existing quests unless they are broken, and even in that case, we probably should preserve them somewhere outside of system/quests/. I assume deleting q068 was just an oversight, but we should restore it before merging.
4. I don't have a strong opinion on preserving superseded quests. If a quest is superseded by a later version (meaning that the earlier version doesn't have any features that the later version lacks, and the earlier version is not "interesting" for another reason), I think it's fine to keep only the latest version.

**Comment by nolrinale** [comment]
quest 68 is not a psobb quest so was only removed from BB but i didnt touched the console versions, I will readd it and MA2 and call it a day from here own you decide what to do with this PR

The permanent versions of the MA quests are always the V2 versions for BB adapted and improved to be replayed all year around, just so you guys know, the others were temporary only for the duration of the MA events

**Comment by Matt-Swift** [comment]
Ultimately it's up to server admins what quests they want to provide - more content is better, so if someone wants the event version of something up (versus the permanent one, or even both), that's up to them.

When it comes to something not being present on a platform originally, having ports of everything to everywhere is always good, as it's more content, and again, if someone doesn't want to provide non-original [platform] quests, that's up to them to remove.

I do kind of agree with fuzzi that it'd be good to have a quest archive of original quests though, as I think it'd be good for newserv to provide ports, improved/fixed original quests, and also custom content, while still having the original quests there for people who would prefer to provide those on their servers.

**Comment by fuzziqersoftware** [comment]
I've manually merged the contents of this PR with master after adjusting the quest numbers and removing some duplicate files.

**Pull request closed without merging**
